export const contactList = [
    {
      id: 1,
      name: "Jacob Seymour",
      profilePic: "/profile/profpic.png",
      lastText: "Hello, how's it going?",
      lastTextTime: "13:33 PM",
    },
    {
      id: 2,
      name: "Pat Kiernan",
      profilePic: "/profile/user1.png",
      lastText: `What's going on bro, we going out?`,
      lastTextTime: "21:46 PM",
    },
    {
      id: 3,
      name: "Laura Cedeno",
      profilePic: "/profile/user2.png",
      lastText: "Te amo 💕",
      lastTextTime: "12:31 AM",
    },
    {
      id: 4,
      name: "Frank White",
      profilePic: "/profile/user3.png",
      lastText: "Dad says hello!",
      lastTextTime: "10:17 AM",
    },
    {
      id: 5,
      name: "Big Chris",
      profilePic: "/profile/user4.png",
      lastText: "Time for beers?",
      lastTextTime: "20:15 PM",
    },
    {
      id: 6,
      name: "Ricardo Fajardo",
      profilePic: "/profile/user5.png",
      lastText: "Did you see the new Tarantino movie?",
      lastTextTime: "15:53 PM",
    },
    {
      id: 7,
      name: "Ryan Patterson",
      profilePic: "/profile/user6.png",
      lastText: `Meet me at the club`,
      lastTextTime: "23:46 PM",
    },
    {
      id: 8,
      name: "Asun Rodriguez",
      profilePic: "/profile/user7.png",
      lastText: "How's life?",
      lastTextTime: "01:24 AM",
    },
    {
      id: 9,
      name: "Max Aarons",
      profilePic: "/profile/user8.png",
      lastText: "Did you watch the Norwich game?",
      lastTextTime: "11:11 AM",
    },
    {
      id: 10,
      name: "Charlie Day",
      profilePic: "/profile/user9.png",
      lastText: "Clean the shed!",
      lastTextTime: "16:22 PM",
    },
  ];

  export const messagesList = [
    {
      id: 1,
      messageType: "TEXT",
      text: "What's up?",
      senderID: 0,
      addedOn: "12:00 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "Not much, you?",
      senderID: 1,
      addedOn: "12:01 PM",
    },
    {
      id: 1,
      messageType: "TEXT",
      text: "Good good, about to go to the football, you coming?",
      senderID: 0,
      addedOn: "12:04 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "Yeah just getting on the tube now!",
      senderID: 1,
      addedOn: "12:04 PM",
    },
    {
      id: 1,
      messageType: "TEXT",
      text: "Great 😁",
      senderID: 0,
      addedOn: "12:10 PM",
    },
    {
      id: 4,
      messageType: "TEXT",
      text: "See you soon! 🍻🍻",
      senderID: 1,
      addedOn: "12:15 PM",
    },
  ];